jobs:
  - name: management
    max_in_flight: 1
    plan:
      - get: dataworks-cognito
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          TF_WORKSPACE: management
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: management
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: management
