jobs:
  - name: dataworks-cognito-pr
    plan:
      - get: dataworks-cognito-pr
        trigger: true
        version: every
      - put: dataworks-cognito-pr
        params:
          path: dataworks-cognito-pr
          status: pending



